#!/bin/bash
#SBATCH --job-name=CNVnator_human_rscript
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:30:00
#SBATCH --mem=24G
#SBATCH --mail-type=all
#SBATCH --output=./error/%x_%A_%a.log
#SBATCH --array=0-11


cd $SLURM_SUBMIT_DIR

#paths and arguments
dir="/path/to/input_files"
outdir="/path/to/outdir"
BIN_SIZE=100000

files=($(find ${dir} -type f -name "*.bam" ))
bam_file=${files[$SLURM_ARRAY_TASK_ID]}
sample_dir=$(dirname "$bam_file")
base_name=$(basename "$bam_file" .bam)
root_file="${sample_dir}/${base_name}_cnvnator.root"
calls_file="${sample_dir}/${base_name}_cnvnator_calls.txt"
tsv_file="${sample_dir}/${base_name}_cnvnator_bins.tsv"

################################################################################
# Load required modules for CNVnator commands
ml purge
ml Anaconda3/2024.06-1
eval "$(conda shell.bash hook)"
conda activate cnvnator

# 1. Extract read mapping
cnvnator -root "$root_file" -tree "$bam_file" -chrom $(seq -f 'chr%g' 1 22) chrX chrY
# 2. Generate histogram
cnvnator -root "$root_file" -his $BIN_SIZE -d /path/to/chrFiles_human
# 3. Calculate statistics
cnvnator -root "$root_file" -stat $BIN_SIZE
# 4. RD SIGNAL PARTITIONING
cnvnator -root "$root_file" -partition $BIN_SIZE
# 5. CNV CALLING
cnvnator -root "$root_file" -call $BIN_SIZE > "$calls_file"

################################################################################
# Load required modules for python scripts
conda deactivate
ml purge
ml Python/3.11.5-GCCcore-13.2.0
ml GATE/10.0.2-foss-2023b
# 6. Run python script - pre-processing root file for visualisation
python /path/to/internship_UGent/scripts/extract_cnvnator_bins.py "$root_file" "$BIN_SIZE" "$tsv_file"

# Load required modules for R script
ml purge
module load R/4.5.2-gfbf-2025b
ml Pandoc/3.6.2
# 7. Run your R script - visualisation
Rscript /path/to/internship_UGent/scripts/CNVnator.R "$base_name" "$outdir" "$BIN_SIZE" "$tsv_file" "$calls_file"
